### ISSUE TITLE
ERROR: start: Timer was not added to the SceneTree. Either add it or set autostart to true.    At: scene/main/timer.cpp:111.

### ISSUE THREAD

**Issue by mrezai** [bruvzg/godot_tl#22]
godot_tl: master
Godot: https://github.com/godotengine/godot/commit/83d950b58e25c401f21b0695a59002fbf6198083
After apply all patches and use_font_wrapper=yes, this error will be printed after add a node to a new scene and select the node:
```
ERROR: start: Timer was not added to the SceneTree. Either add it or set autostart to true.    At: scene/main/timer.cpp:111.
```
I close other old issues and open new ones for better tracking

**Comment by bruvzg** [comment]
Same issue as in vanilla LineEdit, https://github.com/godotengine/godot/issues/31936

**Comment by mrezai** [comment]
Thanks
