### ISSUE TITLE
Underline style doesn't render correctly for different font in the same line

### ISSUE THREAD

**Issue by mrezai** [bruvzg/godot_tl#27]
![Screenshot from 2020-04-09 14-12-09](https://user-images.githubusercontent.com/5120436/78888268-88ea2f80-7a76-11ea-8d7c-61177f7044ed.png)

**Comment by bruvzg** [comment]
Underline should now (382f7a72) use common line baseline, overline and strikethrough are left as is (use glyph ascent/descent, same behaviour as LibreOffice).
