### ISSUE TITLE
Cannot compile module after "patch_lbl_3.x.x.diff" is applied

### ISSUE THREAD

**Issue by xdee** [bruvzg/godot_tl#41]
Godot 3.4-stable
Mac os 12.0.1 (Monterery)
Xcode 13.2.1
Build version 13C100
Mac m1 air

I am trying to compile godot_tl module for 3.4. If I only apply "patch_font_3.x.x.diff" and "patch_editor_font_3.4.x.diff", I can successfully compile the module. However, If I apply "patch_lbl_3.x.x.diff", then the following errors shows and failed to compile.
```
./modules/godot_tl/src/controls/tl_label.hpp:34:10: fatal error: 'resources/tl_font_family.hpp' file not found
#include "resources/tl_font_family.hpp"
```
I think it's some linking problem, but I don't have any knowledge to fix this.
(sorry for my poor english).

Edit: I ran the following command to compile it for osx.
`scons p=osx -j8 use_font_wrapper=true`

**Comment by bruvzg** [comment]
`patch_default_theme_3_4_x.diff` is required to use any of the control changes, these patches are intended to be applied as a set (the latest version of each one except `patch_gdcpp_*.diff`), not individually.

**Comment by xdee** [comment]
Thanks. Solved
